apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-apim-secrets
  namespace: {{ default "default" .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  PORTAL_INITIALUSERS0_PASSWORD: {{ default "wicked" .Values.config.adminPassword | b64enc | quote }}
  GIT_CREDENTIALS: {{ default "" .Values.config.credentials | b64enc | quote }}
  PORTAL_CONFIG_KEY: {{ default "INVALID_CONFIG_KEY" .Values.config.deployKey | b64enc | quote }}
{{- if .Values.redis.deployRedis }}
  PORTAL_SESSIONSTORE_PASSWORD: ""
{{- else }}
  PORTAL_SESSIONSTORE_PASSWORD: {{ default "" .Values.redis.password | b64enc | quote }}
{{- end }}
{{- if .Values.storage.pgUser }}
  PORTAL_STORAGE_PGUSER: {{ .Values.storage.pgUser | b64enc | quote }}
{{- end }}
{{- if .Values.storage.pgPassword }}
  PORTAL_STORAGE_PGPASSWORD: {{ .Values.storage.pgPassword | b64enc | quote }}
{{- end }}
