{{- if .Values.postgres.deployPostgres }}
{{- if and .Values.postgres.persistence.enabled (not .Values.postgres.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-postgres
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.postgres.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- end -}}
{{- end -}}
