{{- if .Values.postgres.deployPostgres }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ template "fullname" . }}-kong-database
    wicked: "true"
  name: {{ template "fullname" . }}-kong-database
  namespace: {{ default "default" .Values.namespace }}
spec:
  ports:
  - name: "psql"
    port: 5432
    protocol: TCP
  selector:
    service: {{ template "fullname" . }}-kong-database
{{- end -}}
