apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-postgres
  namespace: {{ default "default" .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  pgUser: {{ default "kong" .Values.postgres.pgUser | b64enc | quote }}
  pgPassword: {{ default "kong" .Values.postgres.pgPassword | b64enc | quote }}
  pgDatabase: {{ default "kong" .Values.postgres.pgDatabase | b64enc | quote }}
