{{- if .Values.redis.deployRedis }}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ template "fullname" . }}-redis
    wicked: "true"
  name: {{ template "fullname" . }}-redis
  namespace: {{ default "default" .Values.namespace }}
spec:
  ports:
  - name: "redis"
    port: 6379
    protocol: TCP
  selector:
    service: {{ template "fullname" . }}-redis
{{- end -}}
