{{- if .Values.redis.deployRedis }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-redis
  namespace: {{ default "default" .Values.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: {{ template "fullname" . }}-redis
        wicked: "true"
    spec:
{{- if .Values.useRbac }}
      serviceAccountName: {{ template "fullname" . }}-role
{{- end }}
      containers:
      - name: {{ template "fullname" . }}-redis
        image: {{ default "redis:3.2.10-alpine" .Values.redis.image }} 
        ports:
        - name: "redis"
          containerPort: 6379
          protocol: TCP
      restartPolicy: Always
{{- end -}}
